# fly.toml app configuration file generated for binance-csy7wa on 2025-07-02T08:57:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'binance-csy7wa'
primary_region = 'hkg'

[build]

# [http_service]
#   internal_port = 8080
#   force_https = true
#   auto_stop_machines = 'stop'
#   auto_start_machines = true
#   min_machines_running = 1
#   processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
